export const FETCH_NEWSFEED_BEGIN = 'FETCH_NEWSFEED_BEGIN'
export const FETCH_NEWSFEED_SUCCESS = 'FETCH_NEWSFEED_SUCCESS'
export const FETCH_NEWSFEED_FAILURE = 'FETCH_NEWSFEED_FAILURE'

export const FETCH_NEWSFEED_MORE_SUCCESS = 'FETCH_NEWSFEED_MORE_SUCCESS'

export const ADD_NEW_POST = 'ADD_NEW_POST'
