export const FETCH_NEWSFEED_BEGIN = 'FETCH_NEWSFEED_BEGIN'
export const FETCH_NEWSFEED_SUCCESS = 'FETCH_NEWSFEED_SUCCESS'
export const FETCH_NEWSFEED_FAILURE = 'FETCH_NEWSFEED_FAILURE'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'

export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'

export const FETCH_NEWSFEED_MORE_SUCCESS = 'FETCH_NEWSFEED_MORE_SUCCESS'

export const ADD_NEW_POST = 'ADD_NEW_POST'


/**Socket actions */
export const OPEN_NEW_SOCKET = 'OPEN_NEW_SOCKET'
export const CLOSE_SOCKET = 'CLOSE_SOCKET'

/**Authentication actions */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'